= Frequently Asked Questions
:page-authors: gdams, karianna, sxa555, aahlenst, sxa, tellison, kemitix

We have gathered together a few frequently asked questions (FAQs) into
this document.
If you want to talk to us about these topics, or ask additional questions
the best place is via
https://adoptium.net/slack.html[Slack] or by raising an issue in the
https://github.com/adoptium/adoptium-support[support channel].

== Where are the latest JDKs?

Adoptium's JDKs are called Eclipse Temurin, and they are available on
our https://adoptium.net/temurin/releases/[latest releases page].

== Is Eclipse Temurin free to use?

Yes. The Eclipse Temurin binaries are provided by Adoptium at no cost
to you to use, forever. You may freely use, modify, and share the code
as described in the license included in the download.

== How long is Eclipse Temurin supported?

Our release and support statement is available https://adoptium.net/support/[here].

== What happened to AdoptOpenJDK?

The builds you know as AdoptOpenJDK are now "Eclipse Temurin by
Adoptium"(https://blog.adoptium.net/2021/08/adoptium-celebrates-first-release/[release blog post]) Don’t worry though - despite the branding changes it is the same open build processes, AQAvit test
suites and primarily the same team producing them as before, but
there are link:/members[more larger companies] bringing their expertise
to the working group.

To ensure a smooth transition we have left the old site active, however,
the links to latest builds on the old site will now bring you to the
Temurin builds. In time the old website will be fully retired.

Some items, such as the https://adoptopenjdk.net/upstream.html[Upstream builds]
and https://adoptopenjdk.net/icedtea-web.html[IcedTea-WEB] remain only available
via AdoptOpenJDK. We would expect to get lots of complaints if this stuff
just disappeared from view and that would not be the best option for our customers.

== Can you deliver on my favorite Docker base OS image?

We have a set list of variants in our
https://hub.docker.com/_/eclipse-temurin[official Docker repository] to ensure we
are responsive to the delivery of images containing Temurin. Users
who want a containerized Linux distribution that we don’t provide can follow
the instructions in
https://blog.adoptium.net/2021/08/using-jlink-in-dockerfiles/[this
guide].

== What is this "Eclipse Temurin" name?

This is the project and brand name for the binaries that the Eclipse
Foundation produces.
While we appreciate that the Adoptium/Temurin name split
is more confusing that just "Adoptium", this is similar to how other
vendors brand their binaries, e.g. Amazon has Corretto, Azul has Zulu
(and others). The "Adoptium" project and working group will deal with
more than just Temurin so the distinction is important to maintain.

== Where are the OpenJ9 builds?

The transition to Adoptium means we have unfortunately not been able to
continue to distribute builds of Eclipse OpenJ9. IBM has now taken them
over and they are now available as
"https://developer.ibm.com/languages/java/semeru-runtimes/[IBM Semeru]".
There is no need to be concerned about the change - it is still free.

== Where are the Linux RPM/DEB packages?

Linux Installers are available at packages.adoptium.net. For more
information us link:/installation/linux[this guide].

== Why do the packages not include IcedTea-Web?

The agreements that we have since moving under the Eclipse Foundation
mean that we can no longer include IcedTea-Web in our installers.
However, you can still add the functionality if you require it using the
https://blog.adoptopenjdk.net/2018/10/using-icedtea-web-browser-plug-in-with-adoptopenjdk/[instructions
here].

== Can I automate the download of Temurin binaries?

Yes! There is a https://api.adoptium.net/q/swagger-ui/[download API]
provided by Adoptium for downloading Eclipse Temurin builds.

== Can you give a talk on the project?

The people involved in the project are passionate about promoting it and
we are keen to find ways to promote the work we do at Adoptium and with
the Temurin binaries so feel free to get in touch with us if you have a
forum you wish us to participate in and we will see what we can do. In
general contacting the team via Slack is the best way to engage with us.
