= Acerca de Eclipse Adoptium(R)
:page-authors: gdams, karianna, tellison, parkerm, lasombra, hendrikebbers, davew16, akdsco

La misión del proyecto de alto nivel Eclipse Adoptium es producir entornos
de ejecución de alta calidad y la tecnología asociada para su uso en el ecosistema
de Java. Logramos esto a través de un conjunto de proyectos bajo el Adoptium PMC
y una estrecha colaboración con proyectos externos, especialmente con OpenJDK, 
que proporciona la implementación del entorno de ejecución Java SE. Nuestro 
objetivo es satisfacer las necesidades tanto de la comunidad Eclipse como de los
usuarios generales de los entornos de ejecución, proporcionando un conjunto 
completo de tecnologías para aplicaciones Java que operan conforme a los 
estándares existentes, infraestructuras y plataformas en la nube.

El proyecto AdoptOpenJDK fue establecido en 2017 luego de años de discuciones
sobre la falta general de un sistema abierto de compilación y prueba para el 
código fuente de OpenJDK en múltiples plataformas. Desde entonces
ha crecido hasta convertirse en un proveedor lider de 
software de alta calidad basado en los binarios de OpenJDK
utilizados por empresas en sistemas integrados, escritorios, servidores
tradicionales, plataformas modernas en la nube,
y grandes computadores centrales. El proyecto Eclipse Adoptium es la continuación de la misión original de AdoptOpenJDK.

== Alcance

Eclipse Adoptium provee binarios del entorno de ejecución de un alto rendimiento,
calibre empresarial, multiplataforma, con licencia de código abierto, aprobados por Java SE
TCK y compatible para uso general en el ecosistema de Java.
Eclipse Adoptium tambien provee recursos incluyendo infraestructura de código libre, 
un completo sistema de integración continua de compilación  y
pruebas, y extensas pruebas de control de calidad. estos recursos pueden ser utilizados
pro proyectos de Eclipse Adoptium y otros constructores de tecnología de entornos de ejecución
para asegurar la provisión de entornos de ejecución seguros, probados y conformes con Java SE TCK, listos para producción.

The scope of the project includes developing, managing, promoting, and
supporting technologies such as:

* Runtimes and Development Kits: supporting the breadth of APIs
specified by various versions of Java SE, and available on a wide
variety of processor architecture and operating system combinations.
* TCK Testing Infrastructure: providing infrastructure for running Java
SE TCKs to ensure compliance and compatibility.
* JDK Mission Control: low-overhead profiling and diagnostics tools
suite for the JVM.
* Installers and repositories: various mechanisms for obtaining and
managing the installation of runtime technology, such as platform native
installers, container images, download servers, a website, and artifact
repositories.

In addition to providing a reliable source of contemporary Java runtime
binaries, the Eclipse Adoptium project is a platform for experimentation
by developers, academics, and researchers. This provides a place to try
out new runtime, build, test, and infrastructure ideas. Examples of
projects that fall under this top-level project include "jlink.online"
for serving right-sized runtimes to application developers, "Github
actions" to obtain and test with runtimes within Git’s workflow,
"TKG" the test-kit generation framework, "Bumblebench" the
microbenchmarking framework, and more.

== License(s)

* Build scripts and other code to produce the binaries, the website and
other build infrastructure are licensed under https://www.apache.org/licenses/LICENSE-2.0[Apache License, Version 2.0].
* OpenJDK code itself is licensed under https://openjdk.java.net/legal/gplv2+ce.html[GPL v2 with Classpath Exception] (GPLv2+CE) and https://openjdk.java.net/legal/assembly-exception.html[GPL v2 with Assembly Exception] (GPLv2+Assembly).

