= Adoptium(R) 安全软件开发实践
:description: Adoptium 安全软件工程和供应链管理实践
:keywords: Security SSDF SLSA Supply Chain
:orgname: Eclipse Adoptium
:lang: zh-CN
:page-authors: tellison, gdam

Adoptium 项目生成用于关键任务环境的高质量 Java 运行时。对于项目和我们的用户来说，我们提供的软件既安全又可靠是非常重要的。Adoptium 遵循一套基本、健全且安全的软件开发实践，这些实践基于既定的安全软件开发实践，可通过验证来确定我们交付成果的完整性。

== 安全开发实践

我们的安全开发目标是：  

* 确保我们的社区、流程和技术专为安全软件开发而设计。
* 保护流程和软件的所有组件免遭篡改和未经授权的访问。
* 生产安全性良好和安全漏洞最少的软件。
* 适当地应对安全漏洞，并防止将来出现类似的安全漏洞。

Adoptium 通过遵循以下实践来满足这些安全工程目标：

出处和可信来源::
+
Adoptium 从受信任的源代码存储库构建源码，并从受信任的位置获取依赖性和工具。Temurin 构建项目包含用于构建我们的发行版的开源程序或“食谱”，这些构建脚本在虚拟机和操作系统上运行，这些虚拟机和操作系统由项目从可信赖的供应商处采购，并使用来自可信任地点的编译器和安装程序等工具。运行时本身是根据 OpenJDK 和其他著名的第三方项目维护的源代码构建的，这些项目具有强大的治理和监督历史，以确保生成的二进制文件仅包含预期的代码和行为。
+
Adoptium 收集、保护、维护以及共享软件物料清单中每个软件版本的所有组件的出处数据。我们定期验证完整性并检查每个依赖项的来源以识别潜在问题。

版本控制和标记::
+
Adoptium 项目维护的所有代码都保存在 Adoptium 组织下的 Github 版本控制存储库中，并由 Eclipse 基金会管理。我们的源代码是开源的，可供社区审查，但修改代码的权限仅限于当选的、经过严格认证的提交者。我们使用代码存储库的版本控制功能来跟踪对代码所做的所有更改，并对各个提交者的帐户负责，并需要二次审查、额外的自动检查以及社区监督，以确保更改的安全性。
+
Eclipse Temurin 发行版是根据在 OpenJDK 中标记为发行质量的版本控制源构建的，生成的二进制文件作为标记发行版发布在我们的 GitHub 存储库中。

基础设施即代码::
+
为确保基础设施得到安全管理，我们采用基础设施即代码（IaC）原则定义和配置机器。 Adoptium 的大部分构建和测试基础架构都运行在大型云服务提供商运营的虚拟机上。 Adoptium 使用 IaC 定义来定义这些机器的要求和配置，并将其置于 Adoptium 基础设施项目的版本控制之下。 这使得社区能够检查用于生产 Adoptium 产品的基础架构细节，并重复使用这些定义来配置他们信任的机器，以便运行与项目相同的构建和测试软件。
+
IaC 提供了复原能力，可以按照零信任架构配置和实施措施，以确保环境托管基础设施的安全，定义硬件配置的变化，以及在不同供应商上运行我们的基础设施的可用性，从而确保我们有能力每天交叉检查结果。

可重复的构建::
+
Adoptium 安全工程实践的一个重要部分是让社区成员能够验证我们制作的构建。 这可以通过二进制验证的可重现构建来实现，这意味着使用相同的源代码、工具和机器配置，任何人都可以产生字节对字节完全相同的结果。 我们确保我们的源代码、构建脚本和基础架构定义明确、版本受控。 我们发布有关如何重构 Adoptium 二进制文件的信息，并鼓励其他人在相同的输入和流程下，通过检查其构建结果是否匹配来验证这些构建结果。
+
Adoptium 为 Eclipse Temurin 构建的出处提供软件物料清单 (SBOM) 证明。 SBOM 可与我们的每个 Temurin 发布制品一起使用。

测试和代码签名::
+
Adoptium 使用一套广泛的软件测试来验证和检验 Eclipse Temurin 版本。 这些测试由 Adoptium AQAvit 项目负责维护，这些测试旨在确保二进制文件可用于关键生产任务。 AQAvit 测试在发布前检查每个二进制文件的功能正确性、安全位置、性能特征和耐用性。
+
AQAvit 测试既包括项目内部开发的测试，也包括第三方测试套件和应用程序，以确保二进制文件的行为符合预期。 质量保证贯穿整个发布过程，除了严格的发布测试外，还每晚对开发工作进行测试，以确保快速发现并处理异常情况。
+
在 Eclipse Temurin 二进制文件准备发布之前，必须通过 Java 规范符合性测试和 AQAvit 质量保证测试。 只有在完成所有发布测试后，才会发布二进制文件以及支持元数据和软件物料清单。 Adoptium 提供加密安全的代码签名，确保发布的二进制文件是唯一可识别的 Adoptium 正式版本。

审计和核查::
+
除了使用 Oracle 技术兼容性工具包（TCK）进行 Java 兼容性测试外，Adoptium 发布的所有方面都是公开进行的。 TCK 并非开放代码，而且我们与 Oracle 签订的许可证不允许公开进行兼容性测试。 不过，AQAvit 测试全部采用开放源代码，测试结果可供公众监督。 源代码保存在开放源代码库中，所使用的工具在我们的基础架构文件中有所描述。 我们欢迎对项目的构建、测试和发布活动进行审核和验证。
+
Temurin 发布的二进制文件都有一个相应的加密哈希值，终端用户可以通过应用程序接口、网站和 Github 发布库获取。 二进制文件使用由认证机构签发的 Eclipse 代码签名证书进行签名，这样用户的操作系统或其他工具和服务就可以在使用前确认签名的有效性。
+
Adoptium 严肃对待所有安全漏洞，并遵守 Eclipse 基金会漏洞报告政策。 有关产品或安全软件开发实践中潜在或实际漏洞的通知必须遵循该报告政策。
