name: Locale Checker

on:
  workflow_dispatch:
  push:
    paths: [ content/asciidoc-pages/** ]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write

jobs:
  locale-checker:
    if: github.repository_owner == 'adoptium'
    name: Check Locales for Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          persist-credentials: false

      - name: Check asciidoc docs
        run: python3 .github/workflows/locale-checker.py
