name: OSSF Scorecard

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ossf-scorecard:
    uses: adoptium/.github/.github/workflows/ossf-scorecard.yml@main
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
